spring:
  datasource:
    platform: h2
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.h2.Driver
    schema: classpath:db/db_schema.sql
    data: classpath:db/db_data.sql
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: root
    password: 123456
#mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.rxliuli.example.mybatisplussqlinjector.entity.**
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    cache-enabled: false
